version: "3.7"
services:
  db:
    image: postgres:14-alpine
    build:
      dockerfile: ./src/kotlin/db/Dockerfile
    volumes:
      - ./db_data/:/var/lib/postgresql/data
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  manager:
    build: .
    volumes:
      - ./src:/opt/manager
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
volumes:
  postgres_data:
